version: '3.5'

services:
  localstack:
    image: localstack/localstack-full:latest
    container_name: localstack
    hostname: localstack
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
    ports:
      - "4566-4597:4566-4597"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - foobar

  sns-producer:
    build:
      context: ../.
    image: sns-producer:latest
    container_name: sns-producer
    environment:
      - AWS_ENDPOINT=http://localstack:4566
    ports:
      - "8080:8080"
    depends_on:
      - localstack
    networks:
      - foobar

networks:
  foobar:
    name: foobar
    driver: bridge
